# Generated by Django 5.2.17 on 2026-09-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='school.schoolclass', verbose_name='назначенные классы'),
        ),
    ]
