# Generated by Django 5.2.17 on 2026-09-28 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_teacher_school_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='оценка')),
                ('date', models.DateField(verbose_name='дата')),
                ('grade_type', models.CharField(choices=[('current', 'Текущая'), ('exam', 'Экзамен')], default='current', max_length=10, verbose_name='тип оценки')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='комментарий')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.student', verbose_name='ученик')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='school.subject', verbose_name='предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='school.teacher', verbose_name='учитель')),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'оценки',
                'ordering': ['-date', 'student__user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(verbose_name='дата урока')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('late', 'Опоздал')], max_length=10, verbose_name='статус')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='school.student', verbose_name='ученик')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='school.subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'посещение',
                'verbose_name_plural': 'посещаемость',
                'ordering': ['-lesson_date', 'student__user__last_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'lesson_date'), name='unique_attendance_per_student_subject_day')],
            },
        ),
    ]
