# Generated by Django 5.2.17 on 2026-09-28 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_teacher_school_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='день недели')),
                ('time_start', models.TimeField(verbose_name='начало')),
                ('time_end', models.TimeField(verbose_name='окончание')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.schoolclass', verbose_name='класс')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='school.subject', verbose_name='предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='school.teacher', verbose_name='учитель')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'расписание',
                'ordering': ['weekday', 'time_start', 'school_class__name'],
            },
        ),
    ]
